import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { LandingPage } from '@/app/home/LandingPage';
import { Contents } from '@/app/home/Content';

import Footer from '@/app/footer/page';
import TagLine from '@/app/home/TagLine';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <Footer />
      </body>
    </html>
  );
}
